### ISSUE TITLE
pip installation of py-mini-racer fails

### ISSUE THREAD

**Issue by chlarsen** [sqreen/PyMiniRacer#57] opened 2018-07-05 04:59 UTC
Greetings from Vietnam,

### Steps to reproduce
I am running FreeBSD 10.4 with latest updates, and want to install PyMiniRacer as a dependency inside a FreeBSD jail inside a Python 3.6.5 virtual environment. I have installed bash (FreeBSD uses csh by default), as PyMiniRacer seems to depend on it.
pip version is 9.0.3; an upgrade to pip version 10.0.1 does not make any difference.
After clearing the pip cache, I run from inside the virtual environment: 
``````
pip install py-mini-racer
``````

### Expected behavior
pip should download and cleanly install PyMiniRacer inside the virtual environment.

### Actual behavior
Core error message:
``````
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'fetch v8' from working directory /tmp/pip-build-2jgmbfjh/py-mini-racer/py_mini_racer/extension/v8
      File "/tmp/pip-build-2jgmbfjh/py-mini-racer/vendor/depot_tools/fetch.py", line 65
        print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                          ^
    SyntaxError: invalid syntax
``````
Full error message:
``````
(wq) [root@www_py /usr/local/wq]# pip install py-mini-racer
Collecting py-mini-racer
  Downloading https://files.pythonhosted.org/packages/6a/1c/63e74d75cee304e4c534b95e848a45bbd9ef114cc9895dca162206ec29d6/py_mini_racer-0.1.15.tar.gz (327kB)
    100% |████████████████████████████████| 337kB 3.4MB/s 
Installing collected packages: py-mini-racer
  Running setup.py install for py-mini-racer ... error
    Complete output from command /usr/local/wq/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_rx6y13t-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/wq/include/site/python3.6/py-mini-racer:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    copying py_mini_racer/py_mini_racer.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    copying py_mini_racer/__init__.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    copying py_mini_racer/extension/v8_build.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    copying py_mini_racer/extension/__init__.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    running egg_info
    writing py_mini_racer.egg-info/PKG-INFO
    writing dependency_links to py_mini_racer.egg-info/dependency_links.txt
    writing top-level names to py_mini_racer.egg-info/top_level.txt
    reading manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    copying py_mini_racer/extension/mini_racer_extension.cc -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    running build_ext
    running build_v8
    cloning depot tools submodule
    Initialized empty Git repository in /tmp/pip-build-4d1f5b6u/py-mini-racer/.git/
    Cloning into 'vendor/depot_tools'...
    building v8
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'fetch v8' from working directory /tmp/pip-build-4d1f5b6u/py-mini-racer/py_mini_racer/extension/v8
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/vendor/depot_tools/fetch.py", line 65
        print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                          ^
    SyntaxError: invalid syntax
    Traceback (most recent call last):
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py", line 159, in build_extension
        self.run_command('build_v8')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py", line 205, in run
        build_v8(target)
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/py_mini_racer/extension/v8_build.py", line 161, in build_v8
        ensure_v8_src()
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/py_mini_racer/extension/v8_build.py", line 61, in ensure_v8_src
        fetch_v8(path)
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/py_mini_racer/extension/v8_build.py", line 73, in fetch_v8
        call("fetch v8")
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/py_mini_racer/extension/v8_build.py", line 36, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'fetch v8' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py", line 246, in <module>
        'build_v8': MiniRacerBuildV8,
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py", line 176, in build_extension
        raise Exception(err_msg % repr(e))
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
    
                Original error: CalledProcessError(1, 'fetch v8')
    
    ----------------------------------------
Command "/usr/local/wq/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4d1f5b6u/py-mini-racer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_rx6y13t-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/wq/include/site/python3.6/py-mini-racer" failed with error code 1 in /tmp/pip-build-4d1f5b6u/py-mini-racer/
``````

### System configuration
**PyMiniRacer version**:
Tested with 0.1.10 to 0.1.15
**Python version**:
3.6.5
I tried to run the pip installation process from within csh as well as bash, all within the Python 3.6.5 virtual environment.
I am sure I am missing something silly... 

Thank you for any ideas or suggestions!
Chris

**Comment by chlarsen** [comment] 2018-07-09 03:46
Update: After manual installation of python-wheels by isuing: pip3 install wheels, I get this error instead:
``````
  ----------------------------------------
  Failed building wheel for py-mini-racer
  Running setup.py clean for py-mini-racer
  Running setup.py bdist_wheel for unicodecsv ... done
  Stored in directory: /root/.cache/pip/wheels/a6/09/e9/e800279c98a0a8c94543f3de6c8a562f60e51363ed26e71283
  Running setup.py bdist_wheel for formencode ... done
  Stored in directory: /root/.cache/pip/wheels/18/dd/85/119e57aa8207d022581eb5ec40778bd3fa25ecc51520a8147f
Successfully built wq wq.app wq.core wq.db wq.io wq.start pyScss compass-stylesheets PyYAML pystache Pillow requirejs PyBabeljs django-mustache html-json-forms natural-keys psycopg2-binary xlsconv unicodecsv formencode
Failed to build py-mini-racer
Installing collected packages: click, PyYAML, wq.core, six, pyScss, compass-stylesheets, urllib3, idna, certifi, chardet, requests, pystache, Pillow, py-mini-racer, requirejs, PyBabeljs, wq.app, pytz, Django, djangorestframework, django-mustache, html-json-forms, natural-keys, Markdown, wq.db, xlrd, wq.io, psycopg2-binary, unicodecsv, linecache2, traceback2, argparse, unittest2, formencode, pyxform, xlsconv, wq.start, wq
  Running setup.py install for py-mini-racer ... error
    Complete output from command /usr/local/wq/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2l1q7lsh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/wq/include/site/python3.6/py-mini-racer:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    copying py_mini_racer/__init__.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    copying py_mini_racer/py_mini_racer.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer
    creating build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    copying py_mini_racer/extension/__init__.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    copying py_mini_racer/extension/v8_build.py -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    running egg_info
    writing py_mini_racer.egg-info/PKG-INFO
    writing dependency_links to py_mini_racer.egg-info/dependency_links.txt
    writing top-level names to py_mini_racer.egg-info/top_level.txt
    reading manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'py_mini_racer.egg-info/SOURCES.txt'
    copying py_mini_racer/extension/mini_racer_extension.cc -> build/lib.freebsd-10.4-RELEASE-p9-amd64-3.6/py_mini_racer/extension
    running build_ext
    running build_v8
    building v8
    DEBUG:py_mini_racer.extension.v8_build:Calling: 'gclient fetch' from working directory /tmp/pip-install-tw0dz2rm/py-mini-racer/py_mini_racer/extension/v8
    Traceback (most recent call last):
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/vendor/depot_tools/gclient.py", line 99, in <module>
        import urlparse
    ModuleNotFoundError: No module named 'urlparse'
    Traceback (most recent call last):
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py", line 159, in build_extension
        self.run_command('build_v8')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py", line 205, in run
        build_v8(target)
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/py_mini_racer/extension/v8_build.py", line 161, in build_v8
        ensure_v8_src()
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/py_mini_racer/extension/v8_build.py", line 63, in ensure_v8_src
        update_v8(path)
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/py_mini_racer/extension/v8_build.py", line 80, in update_v8
        call("gclient fetch")
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/py_mini_racer/extension/v8_build.py", line 36, in call
        return subprocess.check_call(cmd, shell=True, env=current_env)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'gclient fetch' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py", line 246, in <module>
        'build_v8': MiniRacerBuildV8,
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/wq/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py", line 176, in build_extension
        raise Exception(err_msg % repr(e))
    Exception: py_mini_racer failed to build, ensure you have an up-to-date pip (>= 8.1) to use the wheel instead
                To update pip: 'pip install -U pip'
                See also: https://github.com/sqreen/PyMiniRacer#binary-builds-availability
    
                Original error: CalledProcessError(1, 'gclient fetch')
    
    ----------------------------------------
Command "/usr/local/wq/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tw0dz2rm/py-mini-racer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2l1q7lsh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/wq/include/site/python3.6/py-mini-racer" failed with error code 1 in /tmp/pip-install-tw0dz2rm/py-mini-racer/

``````
Any thoughts? I have read that urlparse has been replaced in Python 3 by urllib.parse, but am not sure where to handle that. Any help would be highly appreciated. Thank you!
 Chris

**Comment by chlarsen** [comment] 2018-07-09 03:49
"fetch v8" seems to be at the core of the problem: When trying:
```````
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
```````
I get:
``````
(wq) [root@www_py /usr/local/wq]# git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 32.61 MiB ...
remote: Total 27005 (delta 17337), reused 27005 (delta 17337)
Receiving objects: 100% (27005/27005), 32.61 MiB | 22.33 MiB/s, done.
Resolving deltas: 100% (17337/17337), done.
(wq) [root@www_py /usr/local/wq]# export PATH=`pwd`/depot_tools:"$PATH"
(wq) [root@www_py /usr/local/wq]# fetch v8
  File "/usr/local/wq/depot_tools/fetch.py", line 65
    print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^
SyntaxError: invalid syntax
``````
Any thoughts?
Thank you,
Chris

**Comment by Congee** [comment] 2018-07-09 05:45
That syntax error is apparently caused by python2

**Comment by chlarsen** [comment] 2018-07-09 07:47
Actually, it is caused by python 3 trying to chew its way through python 2 code, isn't it? Alas, Python 3 is a major dependency of the core application in question (wq).

**Comment by samuelhwilliams** [comment] 2018-07-09 14:56
Also having the same issue here with a fresh install vs Python 3.

**Comment by ningirsu** [comment] 2018-07-10 08:21
Indeed we have an issue here with the setup script which needs python2 in the path. I will try to see how we can improve that.
Else do you know if it's possible to use the wheel on FreeBSD? We have wheel build with https://github.com/pypa/manylinux which should work almost everywhere

**Comment by chlarsen** [comment] 2018-07-10 08:31
Thank you so much for responding, Sélim. Since I installed python-wheel from pypi, the wheel error has gone, and we are (hopefully) left with the requirement to use python 2, instead of python 3 (required by the application I want to install). Let me alert the wq developer, too, as he is the one requiring py-mini-racer for his python 3 application :-). Thanks again for trying to solve this conundrum!
Chris

**Comment by CodingWithErik** [comment] 2018-09-26 21:13
Hello, is there any fix for this yet? Im trying to run Sqreen plugin and pyminiracer is a dependacy, im using python3

**Comment by ningirsu** [comment] 2018-09-27 08:09
@CodingWithErik You should be able to run it without issues in all the supported platform (we provide wheel for that)
This issues appears only if you try to build yourself PyMiniRacer, or we don't have generated the build for your platform

**Closed** 2020-01-21 17:35 UTC
